//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualFinance.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualFinance.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert null value to TargetType of {0}.
        /// </summary>
        internal static string Converter_TargetType_cant_be_null {
            get {
                return ResourceManager.GetString("Converter_TargetType_cant_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetType must be byte array.
        /// </summary>
        internal static string Converter_TargetType_must_be_byte_array {
            get {
                return ResourceManager.GetString("Converter_TargetType_must_be_byte_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetType must be string.
        /// </summary>
        internal static string Converter_TargetType_must_be_string {
            get {
                return ResourceManager.GetString("Converter_TargetType_must_be_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value can not be parsed to a byte array.
        /// </summary>
        internal static string Converter_Value_cant_be_parsed_to_byte_array {
            get {
                return ResourceManager.GetString("Converter_Value_cant_be_parsed_to_byte_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not  be parsed to IFormattable.
        /// </summary>
        internal static string Converter_Value_cant_be_parsed_to_IFormattable {
            get {
                return ResourceManager.GetString("Converter_Value_cant_be_parsed_to_IFormattable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be parsed to a numeric value.
        /// </summary>
        internal static string Converter_Value_cant_be_parsed_to_numeric {
            get {
                return ResourceManager.GetString("Converter_Value_cant_be_parsed_to_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value does not start with &apos;{0}&apos;..
        /// </summary>
        internal static string Converter_Value_has_invalid_prefix {
            get {
                return ResourceManager.GetString("Converter_Value_has_invalid_prefix", resourceCulture);
            }
        }
    }
}
